# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e1a621072386e975d8eb5ff5ecca9e8c200c35818d500242d98675482179057e26a5acc043180990d62a6136cd347a9dc7c14dcd67e62d7e4d62f2db8ef2909

test:
  secret_key_base: 9d2be51d26cfcad91f0c2b3a0adfb9cdb69ae68fd339135f3aa046b812cc9a1c53e059fdf9d77bab1ed3eddd6c6cd441f46c8bbf4e14b68fd52638adda09cec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
